# ---------------------------------------------------------------
# Site Information Settings
# ---------------------------------------------------------------

# Head info
head:
    favicon: "http://ww4.sinaimg.cn/large/72f96cbagw1f5r2v8ovbjj20ma0mawjr.jpg"
    high_res_favicon: "http://ww4.sinaimg.cn/large/72f96cbagw1f5r2v8ovbjj20ma0mawjr.jpg"
    apple_touch_icon: "http://ww4.sinaimg.cn/large/72f96cbagw1f5r2v8ovbjj20ma0mawjr.jpg"
    keywords: "lion1ou lion1ou.win 狮子 前端博客 前端技术"
    site_verification:
        google:
        baidu:

    # Enable generate structured-data as JSON+LD for SEO or not.
    #        Set as 'false' if it cause some wrong when `hexo g`.
    structured_data: true

# Jump Links Settings
url:
    rss:
    daily_pic: "http://lion1ou.win"
    logo: "http://lion1ou.win"


# ---------------------------------------------------------------
# Style Settings
# ---------------------------------------------------------------

# Schemes
scheme: Paradox
# scheme: Isolation

# UI & UX: slogan, color, effect
uiux:
    slogan: "「做一个脚踏实地的前端学徒」"
    theme_color: "#404049"
    theme_sub_color: "#AOAOAF"
    hyperlink_color: "#AOAOAF"
    button_color: "#CBCBD3"
    android_chrome_color: "#404049"
    nprogress_color: "#CBCBD3"
    nprogress_buffer: "800"

# JS Effect Switches
js_effect:
    fade: true
    smoothscroll: false

# Reading experience
reading:
    entry_excerpt: 80

# Thumbnail Settings
thumbnail:
    purecolor:
    random_amount: 19

# Background Settings
# bing available parameter:
#     new | color= | type=
#         color available value: black, blue, brown, green, multi, orange, pink, purple, red, white, yellow
#         type available value: A (animal), C (culture), N (nature), S (space), T (travel)
background:
    purecolor: "#F6F6F6"
    #bgimg: "/img/bg.png"
    bing:
        enable: false
        parameter:

# Images Settings
img:
    logo: "http://ww4.sinaimg.cn/large/72f96cbagw1f5r2v8ovbjj20ma0mawjr.jpg"
    avatar: "http://ww4.sinaimg.cn/large/72f96cbagw1f5r2v8ovbjj20ma0mawjr.jpg"
    daily_pic: "https://ws1.sinaimg.cn/mw690/72a2ccc5gy1fgvlxq4sx5j2334223amt.jpg"
    sidebar_header: "https://ws1.sinaimg.cn/mw690/72a2ccc5gy1fgvlxq4sx5j2334223amt.jpg"
    random_thumbnail: "/img/random/material-"
    footer_image:
        #upyun_logo:
            #link: "https://www.upyun.com/"
            #src: "/img/upyun_logo.svg"

# Custom Fonts
#   family: the font-family which will be used in the theme
#   host: uri of fonts host.
#       Available value of "host": google | baomitu | ustc | custom
fonts:
    family: Roboto, "Helvetica Neue", Helvetica, "PingFang SC", "Hiragino Sans GB", "Microsoft YaHei", "微软雅黑", Arial, sans-serif
    use: google
    custom_font_host:

# Card Elevation Level
card_elevation: 2

# Copyright
# Specify the date when the site was setup.
#   For example, if you set it as 2015, then footer will show '© 2015 - 2017'
copyright_since: 2016

# Qrcode for redirect at other device
#   use: choose which method to generate the qrcode for each posts.
#       Available value of "use": plugin | online
#           - When use "plugin", you need to install the hexo-helper-qrcode.
#           - When use "online", the qrcode will be generated by 'pan.baidu.com' in China.
qrcode:
    enable: true
    use: plugin


# ---------------------------------------------------------------
# Menu Settings
# ---------------------------------------------------------------

# TOC Button

toc:
#   use: choose whether the line_number of toc will show or not.
#       Available value of "linenumber": true | false
    linenumber: true

# SNS Menu
sns:
    email: lion1ou@163.com
    facebook: "https://www.facebook.com/profile.php?id=100010975537330"
    twitter: "https://twitter.com/a418120186"
    # googleplus: "https://www.google.com/"
    weibo: "http://www.weibo.com/1923271877/profile?rightmod=1&wvr=6&mod=personinfo"
    instagram:
    tumblr:
    github: "https://github.com/lion1ou"
    linkedin:
    zhihu: 
    bilibili:
    telegram: 

# SNS Share Switch
sns_share:
    twitter: true
    facebook: true
    googleplus: false
    weibo: true
    linkedin: false
    qq: false
    telegram: false

# Sidebar Customize
sidebar:
    dropdown:
        Email Me:
            link: "mailto:lion1ou@163.com"
            icon: email
    homepage:
        use: true
        icon: home
        divider: false
    archives:
        use: true
        icon: inbox
        divider: false
    categories:
        use: true
        icon: chrome_reader_mode
        divider: false
    
    pages: 
        标签:
            link: "/tags"
            icon: class
            divider: false
        关于:
            link: "/about"
            icon: account_box
            divider: false
        友链:
            link: "/links"
            icon: insert_link
            divider: false
       
    article_num:
        use: true
        divider: false
    footer:
        divider: true
        theme: false
        support: false
        feedback: false
        material: false


# ---------------------------------------------------------------
# Integrated Services
# ---------------------------------------------------------------

# MaterialCDN
# When you set 'use' as true, the needed css, js, font file will have a new src.
# The new src will have the base domain you configured in 'base'.
materialcdn: 
    use: 
    base: 

# Comment Systems
# Available value of "use":
#     disqus | disqus_click | changyan | 163gentie
comment:
    use:
    shortname: # duoshuo or disqus shortname
    changyan_appid:
    changyan_conf:
    changyan_thread_key_type: path
    gentie_productKey: 

# Search Systems
# Available value:
#     swiftype | google | local
search:
    use: google
    swiftype_key:

# Analytics Systems
# Available value:
#     baidu | google | cnzz
analytics:
    use: baidu 
    site_id: 670319318804add6c99a71df6601f645

# Leancloud Views
leancloud:
    enable: true
    app_id: 9mfbTj6RC9Kv7EnYfKxQkUoo-gzGzoHsz #你的 app_id
    app_key: cOjWenbJPVbvvsndlkiRSnU1 #你的 app_key
    av_core_mini: "https://cdn1.lncld.net/static/js/av-core-mini-0.6.1.js"

# Busuanzi 不蒜子 Views
busuanzi:
    enable: true
    all_site_uv: true
    post_pv: true
    busuanzi_pure_mini_js: "https://dn-lbstatics.qbox.me/busuanzi/2.3/busuanzi.pure.mini.js"